# This is a config for E2B sandbox template.
# You can use template ID (jfd6hljngkjefonse95f) or template name (ajay-ai-vibe-coding-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ajay-ai-vibe-coding-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("ajay-ai-vibe-coding-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ajay-ai-vibe-coding-nextjs')

team_id = "c390583f-ad9b-45c9-b446-d9ea4345e192"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ajay-ai-vibe-coding-nextjs"
template_id = "jfd6hljngkjefonse95f"
